site_name: Receitalista
repo_url: https://github.com/mdsreq-fga-unb/2022.2-Receitalista

theme:
    name: material
    language: pt
    features:
        - navigation.tabs
    # logo: ./assets/GDS.png
    # favicon: ./assets/GDS.png
    palette:
        primary: brown
        accent: cyan
        
nav:
  - Home: index.md
  - Documentação: 
    - Visão do produto e projeto: visao-produto.md
    - Backlog do produto - SAFe: backlog_do_produto.md
    - Definição dos MVPs: definicao-mvp.md
    - Produtos gerados por Sprint: produtos-gerados.md
    - Protótipos de baixa fidelidade: prototipos-baixa-fidelidade.md
    - PBB, BDD e User Story Mapping: pbb-bdd-usm.md
    - Casos de Uso: user_cases.md
  - Entregas: entregas.md
